name: Lint - [Frontend]

# Triggers the workflow on pull requests
on:
  pull_request:
  
jobs:
  run-linters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install yarn dependencies and Run ESLint
      run: |
        cd client
        yarn install
        yarn run lint
