
name: Chessboard Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        commit_message: same_commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Install yarn dependencies and Run ESLint
      run: |
        cd client
        yarn install
        yarn run lint --fix
        git config --global user.name 'Eniola Osabiya'
        git config --global user.email 'eni4sure@users.noreply.github.com'
        git commit -m "EsLint Fixes"
        git push

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/zc_plugin_chessboard/
            git stash
            git pull origin dev
            cd server
            yarn install
            yarn build
            PM2_HOME=/opt/pm2/.pm2 pm2 restart index.js
